# Site settings
title: "WorkBlast"
description: "Streamlined shift trading. WorkBlast takes all the hassle out of offering and picking up shifts."
keywords: "shift,trade,schedule"
locale: "en-US"

# Build settings
markdown: kramdown