# Site settings
title: "WorkBlast | Streamlined Shift Trading"
description: "Designed to supplement rather than replace your existing scheduling solution, WorkBlast is a simple tool that allows workers and managers to easily offer and pick up shifts"
keywords: "shift,trade,schedule"
locale: "en-US"

# Build settings
markdown: kramdown